[package]
name = "bible-api"
version = "0.1.0"
authors = ["Debojit Roy <debojit.roy@unohomeloans.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
